jyps_register:
    resource: "@JYPSRegisterBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /member/login
    defaults:  { _controller: JYPSRegisterBundle:Security:login }
    methods:  [POST]

login_check:
    path:   /member/login_check
    methods:  [POST]

logout:
    path:   /member/logout
    methods:  [POST]

member:
    pattern: /member/show/{memberid}
    defaults: { _controller: JYPSRegisterBundle:Member:showAll }
    requirements:
        id:  \d+
    methods:  [POST]

all_members:
    path:   /member
    defaults:  { _controller: JYPSRegisterBundle:Member:index }
    methods:  [GET]

add_member:
    path:   /member/add
    defaults:  { _controller: JYPSRegisterBundle:Member:addMember }
    methods:  [POST]

search:
    path:   /member/search
    defaults:  { _controller: JYPSRegisterBundle:Member:searchMembers }
    methods:  [POST]

searchOld:
    path:   /member/searchOld
    defaults:  { _controller: JYPSRegisterBundle:Member:searchOldMembers }
    methods:  [POST]

join_member:
    path: /join
    defaults:  { _controller: JYPSRegisterBundle:Member:joinMember}
    methods:  [POST]

join_save:
    path: /join/joinSave
    defaults:  { _controller: JYPSRegisterBundle:Member:joinSave}
    methods:  [POST]

join_internal_save:
    path: /member/joinSave
    defaults:  { _controller: JYPSRegisterBundle:Member:joinSaveInternal}
    methods:  [POST]

join_complete:
    path: /join/joinComplete
    defaults: {_controller: JYPSRegisterBundle:Member:joinComplete}
    methods:  [GET]

configuration:
    path: /member/configuration
    defaults: {_controller: JYPSRegisterBundle:Configuration:showAll}
    methods:  [GET]

memberfees:
    path: /member/memberfees
    defaults: {_controller: JYPSRegisterBundle:MemberFee:showAll}
    methods:  [GET]

memberfees_create:
    path: /member/memberfees/create
    defaults: {_controller: JYPSRegisterBundle:MemberFee:createMemberFees}
    methods:  [POST]

end_member:
    path:   /member/end_member
    defaults:  { _controller: JYPSRegisterBundle:Member:endMember}
    methods:  [POST]

mark_member_fees:
    path:   /member/memberfees/showFees
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:showUnpaidFees}
    methods:  [POST]

mark_fees:
    path:   /member/memberfees/markUnpaidFees
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:markFeesPaid}
    methods:  [POST]

showClosed:
    path:   /member/history
    defaults:  { _controller: JYPSRegisterBundle:Member:showClosed}
    methods:  [POST]

restoreMember:
    path:   /member/history/restore
    defaults:  { _controller: JYPSRegisterBundle:Member:restoreMember}
    methods:  [POST]

JYPSRegisterBundle_user:
    resource: "@JYPSRegisterBundle/Resources/config/routing/user.php"
    prefix:   /member/user
    methods:  [POST]

JYPSRegisterBundle_member_intrestconfig:
    resource: "@JYPSRegisterBundle/Resources/config/routing/intrestconfig.php"
    prefix:   /member/intrestconfig
    methods:  [POST]

index_password:
    path:   /member/changePassword
    defaults:  { _controller: JYPSRegisterBundle:PasswordChange:index}
    methods:  [POST]

member_statistics:
    path:   /member/statistics
    defaults:  { _controller: JYPSRegisterBundle:Member:memberStatistics}
    methods:  [POST]

showQuickReports:
    path:   /member/reports
    defaults:  { _controller: JYPSRegisterBundle:Report:index}
    methods:  [POST]

sendReminders:
    path:   /member/memberfees/sendReminders
    defaults:  { _controller: JYPSRegisterBundle:MemberFee:sendReminderLetter}
    methods:  [POST]

exportAddressExcel:
    path:   /member/addressExcel
    defaults:  { _controller: JYPSRegisterBundle:Member:addressExcel}
    methods:  [POST]

memberActions:
    path:   /member/memberactions
    defaults:  { _controller: JYPSRegisterBundle:Member:memberExtra}
    methods:  [GET]

magazineInfo:
    path:   /member/magazineInfo
    defaults:  { _controller: JYPSRegisterBundle:Member:sendMagazineLink}
    methods:  [POST]

communicationMail:
    path:   /member/communicationMail
    defaults:  { _controller: JYPSRegisterBundle:Member:sendCommunicationMail}
    methods:  [POST]

sendCard:
    path:   /member/send_membership_card
    defaults:  { _controller: JYPSRegisterBundle:Member:sendMembershipCard}
    methods:  [POST]

acme_blog:
    type: rest
    prefix: /member/api
    resource: "@JYPSRegisterBundle/Resources/config/routes.yml"  
